export const SCENE_CONFIG = {
  GLOBE_RADIUS: 1.0,
  CLOUD_RADIUS: 1.006,
  ATMOSPHERE_INNER_SCALE: 1.015,
  ATMOSPHERE_OUTER_SCALE: 1.035,
  GLOBE_SEGMENTS: 80,
  SUN_ROTATION_SPEED: 0.02,
  STARFIELD_COUNT: 2000,
} as const;

export const LIGHTING_CONFIG = {
  AMBIENT_INTENSITY: 0.2,
  HEMISPHERE_SKY: "#c8e6ff",
  HEMISPHERE_GROUND: "#0a1628",
  HEMISPHERE_INTENSITY: 0.3,
  SUN_INTENSITY: 1.6,
  SUN_COLOR: "#fff5e6",
  RIM_INTENSITY: 0.3,
  RIM_COLOR: "#6ea8fe",
} as const;

export const CAMERA_CONFIG = {
  DEFAULT_DISTANCE: 2.5,
  ZOOM_DISTANCE: 1.8,
  REGION_ZOOM_DISTANCE: 2.0,
  MIN_DISTANCE: 1.15,
  MAX_DISTANCE: 5,
  ANIM_DURATION: 1000,
  IDLE_TIMEOUT: 5000,
  AUTO_ROTATE_SPEED: 1.0,
  BIRD_ORBIT_SPEED: 0.5,
  DAMPING_FACTOR: 0.08,
  ROTATE_SPEED: 0.5,
  ZOOM_SPEED: 0.8,
} as const;

export const MARKER_CONFIG = {
  RADIUS: 1.02,
  BASE_SCALE: 0.03,
  FLIGHT_RADIUS: 0.015,
  FLIGHT_SPEED: 0.4,
  LOD_DISTANCE: 2.5,
  MAX_3D_MODELS: 15,
  CLICK_ANIM_DURATION: 1300,
} as const;
